[package]
name = "ProofF"
type = "bin"
authors = [""]
compiler_version = ">=0.23.0"

[dependencies]
poseidon2 = { tag = "v0.1.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2"}